#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Rutas para Controlador de Usuario
user:
  path: /usuario
  controller: App\Controller\UserController::index
  methods: [POST]

register:
  path: /register
  controller: App\Controller\UserController::create
  methods: [POST]

login:
  path: /login
  controller: App\Controller\UserController::login
  methods: [POST]

user_edit:
  path: /user/edit
  controller: App\Controller\UserController::edit
  methods: [PUT]

# Rutas para Controlador de Vídeo
video:
  path: /video
  controller: App\Controller\VideoController::index

video_new:
  path: /video/new
  controller: App\Controller\VideoController::newVideo
  methods: [POST]

video_list:
  path: /video/list
  controller: App\Controller\VideoController::videos
  methods: [GET]

video_remove:
  path: /video/remove/{id}
  controller: App\Controller\VideoController::remove
  methods: [DELETE]      