#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Rutas para Controlador de Usuario
user:
  path: /usuario
  controller: App\Controller\UserController::index

# Rutas para Controlador de Vídeo
video:
  path: /video
  controller: App\Controller\VideoController::index
